package com.bda.omnilibrary.model

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize

@Parcelize
data class LogRequest(
    @SerializedName("timestamp") var timestamp: Long? = -1,
    @SerializedName("platform") var platform: String? = null,
    @SerializedName("mac_address") var mac_address: String? = null,
    @SerializedName("category") var category: String? = null,
    @SerializedName("action") var action: String? = null,
    @SerializedName("session_id") var session_id: String? = null,
    @SerializedName("label") var label: String? = null,
    @SerializedName("app_version") var app_version: String? = null,
    @SerializedName("user_id") var user_id: String? = null,
    @SerializedName("uid") var uid: String? = null,
    @SerializedName("user_phone") var user_phone: String? = null,
    @SerializedName("data") var data: String? = null,
    @SerializedName("screen") var screen: String? = null,
    @SerializedName("section_index") var sectionIndex: String? = null,
    @SerializedName("section_type") var sectionType: String? = null,
    @SerializedName("section_name") var sectionName: String? = null,
    @SerializedName("utm_source") var utmSource: String? = null,
    @SerializedName("utm_medium") var utmMedium: String? = null,
    @SerializedName("utm_campaign") var utmCampaign: String? = null,
    @SerializedName("utm_content") var utmContent: String? = null
) : Parcelable {}


@Parcelize
data class LogDataRequest(
    // POP UP
    @SerializedName("SCREEN") var screen: String? = null,
    @SerializedName("MILESTONE ") var milestone: String? = null,
    @SerializedName("POP_UP_UID") var popUpUid: String? = null,
    @SerializedName("TARGET_TYPE") var targetType: String? = null,
    @SerializedName("TARGET_UID") var targetUid: String? = null,
    @SerializedName("TIMESTAMP") var Timestamp: Long? = null,
    @SerializedName("SESSION_ID") var sessionId: String? = null,
    @SerializedName("PREVIOUS_SESSION_ID") var previousSessionId: String? = null,
    @SerializedName("SOURCE") var source: String? = null,
    @SerializedName("MEDIUM") var medium: String? = null,
    @SerializedName("CAMPAIGN") var campaign: String? = null,
    @SerializedName("CONTENT") var content: String? = null,
    @SerializedName("CREATIVE_TYPE") var creative_type: String? = null,
    @SerializedName("CREATIVE_TARGET") var creativeTarget: String? = null,

    // HOME
    @SerializedName("PREVIOUS_SCREEN") var previousScreen: String? = null,
    @SerializedName("DIRECT_BY") var directBy: String? = null,
    @SerializedName("LAYOUT_ID") var layoutId: String? = null,
    @SerializedName("CLICK_FROM") var clickFrom: String? = null,
    @SerializedName("SECTION_INDEX") var sectionIndex: String? = null,
    @SerializedName("SECTION_TYPE") var sectionType: String? = null,
    @SerializedName("SECTION_NAME") var sectionName: String? = null,
    @SerializedName("SECTION_ID") var sectionId: String? = null,
    @SerializedName("LIVE_STREAM_ID") var liveStreamId: String? = null,
    @SerializedName("PROMOTION_ID") var promotionId: String? = null,
    @SerializedName("LIST_CART") var listCart: String? = null,
    @SerializedName("DISPLAY_TYPE") var displayType: String? = null,
    @SerializedName("ITEM_INDEX") var itemIndex: String? = null,
    @SerializedName("ITEM_TYPE") var itemType: String? = null,
    @SerializedName("ITEM_NAME") var itemName: String? = null,
    @SerializedName("ITEM_ID") var itemId: String? = null,
    @SerializedName("CATEGORY") var category: String? = null,
    @SerializedName("ITEM_CATEGORY_NAME") var itemCategoryName: String? = null,
    @SerializedName("ITEM_CATEGORY_ID") var itemCategoryId: String? = null,
    @SerializedName("COLLECTION_TEMP_UID") var collectionTempUid: String? = null,
    @SerializedName("COLLECTION_TEMP_NAME") var collectionTempName: String? = null,
    @SerializedName("CATEGORY_ID") var categoryId: String? = null,
    @SerializedName("COLLECTION_ID") var collectionId: String? = null,
    @SerializedName("COLLECTION_NAME") var collectionName: String? = null,
    @SerializedName("CATEGORY_INDEX") var categoryIndex: String? = null,
    @SerializedName("ITEM_BRAND") var itemBrand: String? = null,
    @SerializedName("ITEM_LIST_PRICE_VAT") var itemListPriceVat: String? = null,
    @SerializedName("CURRENT_PLAYING_TIME") var currentPlayingTime: String? = null,
    @SerializedName("CHILD_CATEGORY") var childCategory: String? = null,
    @SerializedName("CHILD_CATEGORY_ID") var childCategoryId: String? = null,
    @SerializedName("CHILD_CATEGORY_INDEX") var childCategoryIndex: String? = null,
    @SerializedName("LIVE_STREAM_NAME") var liveStreamName: String? = null,
    @SerializedName("PROMOTION_NAME") var promotionName: String? = null,
    @SerializedName("CART_VALUE") var cartValue: String? = null,
    @SerializedName("CART_TOTAL_ITEM") var cartTotalItem: String? = null,
    @SerializedName("TOTAL_ITEM") var totalItem: String? = null,
    @SerializedName("ITEM_NO") var itemNo: String? = null,
    @SerializedName("ITEM_QUANTITY") var itemQuantity: String? = null,
    @SerializedName("VOUCHER_ID") var voucherId: String? = null,
    @SerializedName("VOUCHER_CODE") var voucherCode: String? = null,
    @SerializedName("VOUCHER_VALUE") var voucherValue: String? = null,
    @SerializedName("VALUE") var value: String? = null,
    @SerializedName("DATE") var date: String? = null,
    @SerializedName("MONTH") var month: String? = null,
    @SerializedName("YEAR") var year: String? = null,
    @SerializedName("NAME") var name: String? = null,
    @SerializedName("PHONE") var phone: String? = null,
    @SerializedName("EMAIL") var email: String? = null,
    @SerializedName("SEX") var sex: String? = null,
    @SerializedName("BIRTHDAY") var birthday: String? = null,
    @SerializedName("ADDRESS") var address: String? = null,
    @SerializedName("DISTRICT") var district: String? = null,
    @SerializedName("CITY") var city: String? = null,
    @SerializedName("ADDRESS_TYPE") var addressType: String? = null,
    @SerializedName("INPUT_TYPE") var inputType: String? = null,
    @SerializedName("INPUT_NAME") var inputName: String? = null,
    @SerializedName("KEY_ID") var keyId: String? = null,
    @SerializedName("KEY_NAME") var KeyName: String? = null,
    @SerializedName("MENU_NAME") var menuName: String? = null,
    @SerializedName("TAB_NAME") var tabName: String? = null,
    @SerializedName("TAB_INDEX") var tabIndex: String? = null,
    @SerializedName("POP_UP_NAME") var popUpName: String? = null,
    @SerializedName("ADDRESS_ID") var addressId: String? = null,
    @SerializedName("RECIPIENT_NAME") var recipientName: String? = null,
    @SerializedName("RECIPIENT_PHONE") var recipientPhone: String? = null,
    @SerializedName("RECIPIENT_ADDRESS") var recipientAddress: String? = null,
    @SerializedName("RECIPIENT_DISTRICT") var recipientDistrict: String? = null,
    @SerializedName("RECIPIENT_CITY") var recipientCity: String? = null,
    @SerializedName("RECIPIENT_ADDRESS_TYPE") var recipientAddressType: String? = null,
    @SerializedName("IS_DEFAULT") var isDefault: String? = null,
    @SerializedName("ORDER_ID") var orderId: String? = null,
    @SerializedName("ORDER_STATUS") var orderStatus: String? = null,
    @SerializedName("ORDER_PAY_STATUS") var orderPayStatus: String? = null,
    @SerializedName("ORDER_VALUE") var orderValue: String? = null,
    @SerializedName("ATTACHMENT_TYPE") var attachmentType: String? = null,
    @SerializedName("ATTACHMENT_URL") var attachmentUrl: String? = null,
    @SerializedName("INPUT_TEXT") var inputText: String? = null,
    @SerializedName("PAYMENT_METHOD_NAME") var paymentMethodName: String? = null,
    @SerializedName("REASON") var reason: String? = null,
    @SerializedName("RESULT") var result: String? = null,
    @SerializedName("KEYWORD") var keyword: String? = null,
    @SerializedName("BRANDSHOP_NAME") var brandshopName: String? = null,
    @SerializedName("BRANDSHOP_UID") var brandshopUid: String? = null,
    @SerializedName("HYBRID_UID") var hybridUid: String? = null,
    @SerializedName("HYBRID_SECTION_VALUE") var hybridUidSectionValue: String? = null,
    @SerializedName("HYBRID_SECTION_NAME") var hybridUidSectionName: String? = null,
    @SerializedName("HYBRID_SECTION_REF") var hybridUidSectionRef: String? = null,
    @SerializedName("HYBRID_SECTION_TYPE") var hybridUidSectionType: String? = null
    ) : Parcelable {}
